### PR TITLE
set only official url

### PR DESCRIPTION
**Pull request by ccarruitero**

### CODE REVIEW

**Comment by skyschub** [comment]
Erm... login.dev.anosrep.org is the [official](https://developer.mozilla.org/en-US/docs/Persona/Implementing_a_Persona_IdP#Testing_against_pre-release_versions_of_Persona) development server and there is nothing wrong with using it. One thing I might consider merging is a change to `login.anosrep.org` instead of `login.dev.anosrep.org` to get the same server versions in both environments, but it _should_ be fine the way it is right now.

Why is this an issue for you?

**Comment by ccarruitero** [comment]
Well I think is better use the same server in development and in production for gem. Maybe set this in initializer?

**Comment by skyschub** [comment]
Hi, sorry for my late replay, I was kinda busy. I'd be fine with setting the URL in the initializer!

**Comment by ccarruitero** [comment]
close this in favor other pull request

**Pull request closed without merging**
